app:
  name: "Fire Salamander"
  version: "1.0.0"
  icon: "🔥"
  powered_by: "SEPTEO"

branding:
  primary_color: "#ff6b35"
  secondary_color: "#2c3e50"
  neutral_colors: ["#f8f9fa", "#e1e8ed", "#7f8c8d"]

server:
  port: 8080

database:
  type: "sqlite"
  path: "data/firesalamander.db"

crawler:
  workers: 2
  rate_limit: "10/s"
  user_agent: "Fire Salamander SEO Analyzer/1.0"

ai:
  enabled: false
  mock_mode: true
  model: "gpt-3.5-turbo"
  max_tokens: 1000
  timeout: 30
  use_cache: true
  cache_ttl: 3600