version: '3.8'

services:
  app:
    build: .
    container_name: firesalamander
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
      - "/app/data"
    working_dir: /app
    environment:
      - ENV=development
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: firesalamander-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: firesalamander
      MYSQL_USER: firesalamander
      MYSQL_PASSWORD: firesalamander
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: