app:
  name: "Fire Salamander"
  version: "1.0.0"
  icon: "🦎"
  powered_by: "SEPTEO"
  
branding:
  primary_color: "#ff6136"  # Orange SEPTEO
  secondary_color: "#1e3a8a" # Bleu corporate
  neutral_colors: ["#f5f5f5", "#e5e5e5", "#737373", "#262626"]
  
server:
  port: 8080
  
database:
  type: mysql
  host: localhost
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASS}
  
crawler:
  workers: 4
  rate_limit: 2/s
  user_agent: "FireSalamander/1.0 (SEPTEO) SEO Analyzer"
  
ai:
  enabled: true
  mock_mode: false  # Production utilise la vraie API
  api_key: "${OPENAI_API_KEY}"  # Variable d'environnement
  model: "gpt-3.5-turbo"  # Modèle économique
  max_tokens: 800  # Moins de tokens en prod pour économiser
  timeout: 30
  use_cache: true
  cache_ttl: 7200  # 2 heures de cache en prod